import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Sidebar from './components/sidebar/sidebar.jsx';

const roboto = Roboto({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" className={`${roboto.variable} ${roboto.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <main>
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
