import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '../provider/auth-provider';
import Sidebar from '../components/sidebar/sidebar';

const roboto = Roboto({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" className={`${roboto.variable} ${roboto.variable} min-h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <main>
            <Sidebar />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
