import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '../provider/auth-provider';
import Sidebar from '../components/sidebar/sidebar';
import { Toaster } from 'sonner';
const roboto = Roboto({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" className={`${roboto.variable} ${roboto.variable} min-h-full antialiased`}>
      <body className="min-h-screen">
        <AuthProvider>
          <Sidebar />

          <main className="ml-64 min-h-screen p-8">{children}</main>

          <Toaster richColors position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
